[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "iex-parser"
version = "0.1.6"
description = "A package with a C++ module"
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.19.2",
]
requires-python = ">=3.7"

[tool.hatchling.build-config]
include = [
    "iex_parser/*",
]

[tool.hatch.build.targets.wheel.force-include]
"iex_parser/iex_parser.out" = "iex_parser/iex_parser.out"

